name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "*.html,*.php,*.json,nginx/**"
          target: "/usr/share/nginx/html"
          
      - name: Set file permissions
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            chown -R nginx:nginx /usr/share/nginx/html/
            chmod 755 /usr/share/nginx/html/*.html
            chmod 755 /usr/share/nginx/html/*.php
            chmod 666 /usr/share/nginx/html/content.json 