name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "*.html,*.php,*.json,nginx/**"
          target: "/usr/share/nginx/html"
          
      - name: Set file permissions and configure nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            # 设置文件权限
            chown -R nginx:nginx /usr/share/nginx/html/
            chmod 755 /usr/share/nginx/html/*.html
            chmod 755 /usr/share/nginx/html/*.php
            chmod 666 /usr/share/nginx/html/content.json
            
            # 复制并应用 nginx 配置
            if [ -f /usr/share/nginx/html/nginx/nginx.conf ]; then
              cp /usr/share/nginx/html/nginx/nginx.conf /etc/nginx/nginx.conf
              nginx -t && systemctl restart nginx
            fi 