name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "*.php,config.php,db.php,nginx/**,vendor/**,composer.json,composer.lock,db/**"
          target: "/usr/share/nginx/html"

      - name: Configure Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          envs: MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
          script: |
            # 确保密码文件存在并设置正确权限
            echo '${{ secrets.MYSQL_ROOT_PASSWORD }}' | sudo tee /etc/mysql_root_password > /dev/null
            sudo chown nginx:nginx /etc/mysql_root_password
            sudo chmod 600 /etc/mysql_root_password
            
            # 设置文件权限
            chown -R nginx:nginx /usr/share/nginx/html/
            chmod 755 /usr/share/nginx/html/*.html
            chmod 755 /usr/share/nginx/html/*.php
            chmod 644 /usr/share/nginx/html/nginx/*.conf 
            sudo cp /usr/share/nginx/html/nginx/conf.d/default.conf /etc/nginx/conf.d/
            sudo cp /usr/share/nginx/html/nginx/nginx.conf /etc/nginx/nginx.conf
            sudo systemctl restart nginx 